from sage.events.bus import EventBus

EXECUTE_UNVERIFIED = "EXECUTE_UNVERIFIED"
EXECUTE_HALTED_UNVERIFIED = "EXECUTE_HALTED_UNVERIFIED"
EXECUTE_BUDGET_EXCEEDED = "EXECUTE_BUDGET_EXCEEDED"
PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"

__all__ = [
    "EventBus",
    "EXECUTE_UNVERIFIED",
    "EXECUTE_HALTED_UNVERIFIED",
    "EXECUTE_BUDGET_EXCEEDED",
    "PROMPT_INJECTION_DETECTED",
]
