"""Regenerate `docs/CLAIMS.yaml` from `docs/claims/*.yaml`.

Cycle-13 K Phase 0.1a: `docs/CLAIMS.yaml` is a generated, README-friendly
aggregate of all per-category YAML files. Editing it directly is forbidden
— this script overwrites it. Edit the per-category file under
`docs/claims/` instead.

Usage:
  python scripts/regenerate_claims_index.py             # write the file
  python scripts/regenerate_claims_index.py --check     # exit 1 if drifted
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml  # type: ignore[import-untyped]

_HEADER = """# AUTOGENERATED — do not edit directly.
#
# Source files: docs/claims/*.yaml
# Regenerator:  scripts/regenerate_claims_index.py
#
# Generated_at_utc is updated on every run; the canonical hashable diff is the
# `claims:` array, which is sorted by id for stable output.
"""


def _claims_dir(repo_root: Path) -> Path:
    return repo_root / "docs" / "claims"


def _index_path(repo_root: Path) -> Path:
    return repo_root / "docs" / "CLAIMS.yaml"


def collect_all(repo_root: Path) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for yaml_path in sorted(_claims_dir(repo_root).glob("*.yaml")):
        if yaml_path.name == "CLAIMS.yaml":
            continue
        payload = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict) or not isinstance(payload.get("claims"), list):
            continue
        for entry in payload["claims"]:
            if isinstance(entry, dict) and "id" in entry:
                # _source_file is informational only — included so a reader
                # of the index can find the per-category file to edit.
                entry = {
                    **entry,
                    "_source_file": str(yaml_path.relative_to(repo_root)).replace("\\", "/"),
                }
                out.append(entry)
    out.sort(key=lambda c: c.get("id", ""))
    return out


def render(claims: list[dict[str, Any]]) -> str:
    payload = {
        "_generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "_total_claims": len(claims),
        "claims": claims,
    }
    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=100)
    return _HEADER + "\n" + body


def _find_repo_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in (current, *current.parents):
        if (candidate / "docs" / "claims").is_dir():
            return candidate
    return start.resolve()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/CLAIMS.yaml from per-category files.")
    parser.add_argument("--check", action="store_true", help="Exit 1 if regeneration would change the file.")
    parser.add_argument("--repo-root", type=Path, default=None)
    args = parser.parse_args(argv)

    repo_root = args.repo_root if args.repo_root else _find_repo_root(Path.cwd())
    claims = collect_all(repo_root)
    rendered = render(claims)

    target = _index_path(repo_root)
    if args.check:
        # In --check mode we ignore the volatile `_generated_at_utc` line:
        # we only care about the claims content.
        if not target.is_file():
            print(f"FAIL: {target} does not exist (run without --check to generate).")
            return 1
        existing = target.read_text(encoding="utf-8")
        if _strip_volatile(existing) == _strip_volatile(rendered):
            print(f"OK: {target} is up to date.")
            return 0
        print(f"FAIL: {target} is stale; run `python scripts/regenerate_claims_index.py`.")
        return 1

    target.write_text(rendered, encoding="utf-8")
    print(f"Wrote {target} — {len(claims)} claims.")
    return 0


def _strip_volatile(text: str) -> str:
    """Drop lines that change every run (timestamp) so --check is stable."""
    return "\n".join(
        line for line in text.splitlines() if not line.strip().startswith("_generated_at_utc:")
    )


if __name__ == "__main__":
    sys.exit(main())
