//! DynamicTopologyEngine — central orchestrator for task-adaptive topology generation.
//!
//! Ties together S-MMU retrieval, MAP-Elites archive lookup, mutation, LLM synthesis,
//! and evolution for generating custom multi-agent DAGs per task.
//!
//! # 6-path strategy (priority order)
//!
//! 1. **S-MMU hit**: Retrieve similar past task from S-MMU. If similarity > 0.7 AND quality > 0.5,
//!    clone that topology. Inject bandit priors.
//! 2. **Archive hit**: Compute `BehaviorDescriptor` from task heuristics, look up MAP-Elites archive.
//!    If found AND quality > 0.5, use it.
//! 3. **LLM synthesis**: Skip in pure Rust (Python side calls synthesize() directly).
//! 4. **Mutation**: Pick best-by-quality from archive, apply random mutation.
//! 5. **Template fallback**: S1→sequential, S2→avr, S3→debate.

use rand::Rng;
use std::collections::HashMap;
use tracing::{debug, info, info_span, warn};

use crate::memory::smmu::MultiViewMMU;
use crate::routing::bandit::ContextualBandit;

use super::cma_me::{CmaEmitter, DimensionBounds};
use super::llm_synthesis::TopologySynthesizer;
use super::map_elites::{BehaviorDescriptor, MapElitesArchive};
use super::mcts::MctsSearcher;
use super::mutations::{apply_mutation_tracked, MutationResult, MutationStats};
use super::smmu_bridge::{TopologyOutcome, TopologySmmuBridge};
use super::templates;
use super::topology_graph::TopologyGraph;
use super::verifier::HybridVerifier;

// ── TopologySource ────────────────────────────────────────────────────────

/// How a topology was obtained by the engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TopologySource {
    /// Retrieved from similar past task via S-MMU.
    SmmuHit,
    /// Found in MAP-Elites archive.
    ArchiveHit,
    /// Generated by LLM (Python side).
    LlmSynthesis,
    /// Mutated from an existing topology.
    Mutation,
    /// Found via MCTS search over mutation space.
    MctsSearch,
    /// Fell back to a built-in template.
    TemplateFallback,
}

impl TopologySource {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::SmmuHit => "smmu_hit",
            Self::ArchiveHit => "archive_hit",
            Self::LlmSynthesis => "llm_synthesis",
            Self::Mutation => "mutation",
            Self::MctsSearch => "mcts_search",
            Self::TemplateFallback => "template_fallback",
        }
    }
}

// ── GenerateResult ────────────────────────────────────────────────────────

/// Result of `TopologyEngine::generate()`.
#[derive(Debug)]
pub struct GenerateResult {
    /// The generated topology graph.
    pub topology: TopologyGraph,
    /// How the topology was obtained.
    pub source: TopologySource,
    /// Confidence in the topology quality [0.0, 1.0].
    pub confidence: f32,
}

// ── TopologyEngine ────────────────────────────────────────────────────────

/// Central engine that orchestrates S-MMU retrieval, archive lookup, mutation,
/// LLM synthesis, and evolution for task-adaptive custom DAG generation.
// PRIMARY topology engine — 6-path generation used by boot.py Phase 6 + Pipeline Stage 2.
pub struct TopologyEngine {
    bridge: TopologySmmuBridge,
    archive: MapElitesArchive,
    verifier: HybridVerifier,
    synthesizer: TopologySynthesizer,
    bandit: ContextualBandit,
    /// CMA-ME emitter for continuous parameter optimisation (cost, time, edge weight).
    cma_emitter: CmaEmitter,
    /// All known topologies by ULID id, for lazy-load from RoutingDecision.
    topology_cache: HashMap<String, TopologyGraph>,
    /// Last bandit decision_id from generate(), used by record_outcome() to update posteriors.
    last_decision_id: Option<String>,
    /// Number of outcomes recorded since the last `evolve()` call.
    /// Used by `should_evolve()` to enforce a cooldown between evolution passes.
    outcomes_since_last_evolve: usize,
    /// Thompson sampling stats per mutation operator (Fix 1).
    /// Tracks success rates to prefer operators that produce valid topologies.
    /// Mutex for thread-safe interior mutability — stats updated in &self methods.
    mutation_stats: std::sync::Mutex<MutationStats>,
    /// Ring buffer of operator names applied during the most recent `evolve()`
    /// pass — one entry per child mutation attempt (not per child, since
    /// `evolve()` may apply 1-3 mutations per candidate). Drained by Python
    /// via `PyTopologyEngine.drain_last_applied_ops()` so the pipeline can log
    /// `evolution.mutation.applied` lines after the evolve call returns.
    ///
    /// Capped at 1024 entries (FIFO eviction) to cap memory even on
    /// pathological evolve configurations.
    last_applied_ops: std::sync::Mutex<Vec<String>>,
}

impl TopologyEngine {
    /// Create a new engine with default bandit (decay=0.995, exploration=0.1).
    pub fn new() -> Self {
        Self {
            bridge: TopologySmmuBridge::new(),
            archive: MapElitesArchive::new(),
            verifier: HybridVerifier::new(),
            synthesizer: TopologySynthesizer::new(),
            bandit: ContextualBandit::create(0.995, 0.1),
            cma_emitter: CmaEmitter::with_bounds(
                3,
                0.3,
                vec![
                    DimensionBounds::new(0.001, 5.0), // max_cost_usd
                    DimensionBounds::new(1.0, 300.0), // max_wall_time_s
                    DimensionBounds::new(0.1, 5.0),   // edge_weight
                ],
                0.99, // sigma decay — subject to ablation
            ),
            topology_cache: HashMap::new(),
            last_decision_id: None,
            outcomes_since_last_evolve: 0,
            mutation_stats: std::sync::Mutex::new(MutationStats::new()),
            last_applied_ops: std::sync::Mutex::new(Vec::new()),
        }
    }

    /// Take ownership of the list of mutation operator names applied during
    /// the most recent `evolve()` call. Clears the internal buffer so
    /// subsequent `evolve()` calls start fresh.
    ///
    /// Order is generation-major, candidate-major: every attempt inside the
    /// per-child 1..=3 inner loop pushes exactly one entry, regardless of
    /// whether the attempt produced a valid graph.
    pub fn drain_last_applied_ops(&self) -> Vec<String> {
        let mut guard = self.last_applied_ops.lock().unwrap();
        std::mem::take(&mut *guard)
    }

    /// Read-only snapshot of the per-operator Thompson-sampling stats.
    /// Returns `(op_name, attempts, successes, alpha, beta)` for each of the
    /// 7 operators in the same order as `OPERATOR_NAMES`.
    pub fn mutation_stats_snapshot(&self) -> Vec<(String, u32, u32, f64, f64)> {
        let stats = self.mutation_stats.lock().unwrap();
        super::mutations::OPERATOR_NAMES
            .iter()
            .enumerate()
            .map(|(i, name)| {
                (
                    (*name).to_string(),
                    stats.attempts(i),
                    stats.successes(i),
                    stats.alpha(i),
                    stats.beta(i),
                )
            })
            .collect()
    }

    /// Accessor: read-only reference to the MAP-Elites archive.
    pub fn archive(&self) -> &MapElitesArchive {
        &self.archive
    }

    /// Accessor: read-only reference to the contextual bandit.
    pub fn bandit(&self) -> &ContextualBandit {
        &self.bandit
    }

    /// Accessor: read-only reference to the S-MMU bridge.
    pub fn bridge(&self) -> &TopologySmmuBridge {
        &self.bridge
    }

    /// Store a topology in the cache by its id.
    ///
    /// Evicts lowest-quality entries (by node+edge count) if the cache exceeds 500 topologies.
    pub fn cache_topology(&mut self, graph: TopologyGraph) {
        if self.topology_cache.len() >= 500 {
            // Evict lowest-quality entries (fewest nodes+edges) to keep rich topologies.
            let mut scored: Vec<(String, usize)> = self
                .topology_cache
                .iter()
                .map(|(id, g)| (id.clone(), g.node_count() + g.edge_count()))
                .collect();
            scored.sort_by_key(|(_, score)| *score);
            // Remove bottom half (lowest complexity)
            for (key, _) in scored.into_iter().take(250) {
                self.topology_cache.remove(&key);
            }
        }
        self.topology_cache.insert(graph.id.clone(), graph);
    }

    /// Number of cached topologies.
    pub fn topology_count(&self) -> usize {
        self.topology_cache.len()
    }

    /// Lazy-load a topology from cache by ULID id.
    pub fn get_topology(&self, id: &str) -> Option<&TopologyGraph> {
        self.topology_cache.get(id)
    }

    // ── Core generation ───────────────────────────────────────────────────

    /// Generate a topology for a task using the 6-path strategy.
    ///
    /// # Arguments
    /// - `smmu`: The multi-view S-MMU for context retrieval.
    /// - `task_description`: Human-readable task description.
    /// - `task_embedding`: Optional 768-dim embedding for semantic search.
    /// - `system`: Cognitive system tier (1=S1, 2=S2, 3=S3).
    /// - `exploration_budget`: 0.0 = pure exploit, 1.0 = pure explore.
    pub fn generate(
        &mut self,
        smmu: &mut MultiViewMMU,
        task_description: &str,
        task_embedding: Option<Vec<f32>>,
        system: u8,
        exploration_budget: f32,
    ) -> GenerateResult {
        let _span = info_span!(
            "topology_engine.generate",
            system = system,
            exploration_budget = exploration_budget,
            task_len = task_description.len(),
        )
        .entered();

        // ── Bandit-guided exploration budget ──────────────────────────────────
        // Move bandit.choose() BEFORE the 6-path cascade so the bandit
        // *influences* path selection rather than merely recording it.
        // When the bandit has enough arms (>3) and returns a high-confidence
        // decision, we reduce the exploration budget to exploit known-good
        // paths. During cold start we keep the caller's budget unchanged.
        let effective_budget = if self.bandit.arm_count() > 3 {
            if let Ok(d) = self.bandit.choose(exploration_budget) {
                self.last_decision_id = Some(d.decision_id.clone());
                // High expected quality → reduce exploration (exploit).
                // Low expected quality  → keep exploration high.
                let confidence_factor = 1.0 - d.expected_quality.clamp(0.0, 1.0);
                let modulated = exploration_budget * (0.3 + 0.7 * confidence_factor);
                debug!(
                    original_budget = exploration_budget,
                    effective_budget = modulated,
                    bandit_quality = d.expected_quality,
                    "bandit_modulated_exploration"
                );
                modulated
            } else {
                exploration_budget
            }
        } else {
            // Cold start — full caller-specified exploration
            self.last_decision_id = None;
            exploration_budget
        };

        // Path selection: bandit-guided exploration.
        // When effective_budget > 0.5, skip retrieval paths (S-MMU, archive)
        // and go straight to generative paths (mutation, MCTS) to discover new topologies.
        // Threshold 0.35: with EXPLORATION_BUDGET_HIGH=0.50 and bandit modulation
        // (0.3 + 0.7*confidence), effective_budget ranges [0.09, 0.50].
        // At 0.35, exploration triggers when bandit has low confidence (quality < 0.43).
        let skip_retrieval = effective_budget > 0.35;

        // Path 1: S-MMU hit — retrieve similar past task (skip if exploring)
        let result = if !skip_retrieval {
            if let Some(result) = self.try_smmu_hit(smmu, task_description, task_embedding.clone())
            {
                info!(
                    source = "smmu_hit",
                    confidence = result.confidence,
                    "topology_generated"
                );
                Some(result)
            } else {
                None
            }
        } else {
            debug!("smmu_path_skipped_by_bandit_exploration");
            None
        };

        // Path 2: Archive hit — look up MAP-Elites (skip if exploring)
        let result = result.or_else(|| {
            if !skip_retrieval {
                if let Some(r) = self.try_archive_hit(system, task_description) {
                    info!(
                        source = "archive_hit",
                        confidence = r.confidence,
                        "topology_generated"
                    );
                    return Some(r);
                }
            } else {
                debug!("archive_path_skipped_by_bandit_exploration");
            }
            None
        });

        // Path 4: Mutation — mutate best-by-quality from archive
        // Path 3: LLM synthesis — skipped in pure Rust (Python calls synthesize() directly)
        let result = result.or_else(|| {
            if let Some(r) = self.try_mutation() {
                info!(
                    source = "mutation",
                    confidence = r.confidence,
                    "topology_generated"
                );
                return Some(r);
            }
            None
        });

        // Path 5: MCTS search (if archive has enough diversity)
        let result = result.or_else(|| {
            if let Some(r) = self.try_mcts_search() {
                info!(
                    source = "mcts_search",
                    confidence = r.confidence,
                    "topology_generated"
                );
                return Some(r);
            }
            None
        });

        // Path 6: Template fallback — ALWAYS succeeds, unwrap the Option chain.
        // Path 3 hint: LLM synthesis deferred to Python side.
        let result = result.unwrap_or_else(|| {
            if effective_budget > 0.3 && !self.synthesizer.is_rate_limited() {
                debug!("llm_synthesis_path_available_but_deferred_to_python");
            }
            let fb = self.template_fallback(system);
            info!(
                source = "template_fallback",
                confidence = fb.confidence,
                template = fb.topology.template_type.as_str(),
                "topology_generated"
            );
            fb
        });

        // Register the chosen path as a bandit arm so future decisions
        // can reason about this source/template combination.
        // choose() was already called BEFORE the cascade (above), so we
        // do NOT call it again here — just register the observed arm.
        let source_str = result.source.as_str();
        self.bandit
            .add_arm(source_str, &result.topology.template_type);

        result
    }

    /// Path 1: Try to find a similar past task in S-MMU.
    fn try_smmu_hit(
        &mut self,
        smmu: &mut MultiViewMMU,
        _task_description: &str,
        _task_embedding: Option<Vec<f32>>,
    ) -> Option<GenerateResult> {
        let _span = info_span!("topology_engine.smmu_path").entered();

        // Need at least one chunk in the bridge to retrieve from
        if self.bridge.chunk_count() == 0 {
            debug!("smmu_path_skip_empty_bridge");
            return None;
        }

        // Register task as a query chunk in S-MMU to compare against stored outcomes.
        // We create a temporary MMU to hold the query so we don't mutate the shared one.
        // Instead, use the existing smmu directly for retrieval — register a temporary
        // query chunk would require &mut, which we don't have. So we scan bridge metadata
        // for the best match based on quality alone (simplified path).
        //
        // The full S-MMU semantic retrieval requires mutable access to register the query
        // chunk. Since `generate()` takes `&MultiViewMMU` (immutable), we fall through to
        // archive or mutation paths. The Python layer can call retrieve_similar() with a
        // properly registered query chunk before calling generate().

        // Use last registered chunk as query anchor; fall through if none registered
        let anchor = smmu.last_chunk_id().unwrap_or_default().to_string();
        let suggestions = self.bridge.retrieve_similar(smmu, &anchor, 5);

        // Find best suggestion with similarity > 0.7 AND quality > 0.5
        let best = suggestions
            .iter()
            .filter(|s| s.similarity_score > 0.7 && s.quality > 0.5)
            .max_by(|a, b| {
                a.similarity_score
                    .partial_cmp(&b.similarity_score)
                    .unwrap_or(std::cmp::Ordering::Equal)
            });

        if let Some(suggestion) = best {
            // Inject priors into bandit from all high-quality suggestions
            self.bridge.inject_priors(&mut self.bandit, &suggestions);

            // Try to clone the topology from cache
            if let Some(cached) = self.topology_cache.get(&suggestion.topology_id) {
                let topology = cached.clone();
                let confidence = suggestion.similarity_score * suggestion.quality;
                info!(
                    topology_id = %suggestion.topology_id,
                    similarity = suggestion.similarity_score,
                    quality = suggestion.quality,
                    "smmu_hit_found"
                );
                return Some(GenerateResult {
                    topology,
                    source: TopologySource::SmmuHit,
                    confidence,
                });
            }

            debug!(
                topology_id = %suggestion.topology_id,
                "smmu_hit_topology_not_in_cache"
            );
        }

        None
    }

    /// Path 2: Try to find a topology in the MAP-Elites archive.
    ///
    /// Uses the cognitive system tier (S1/S2/S3) from kNN routing (92%
    /// accuracy) as the sole complexity signal.  Previous versions used
    /// `task_description.len()` as a proxy for complexity, but task length
    /// is a terrible heuristic — short tasks can be highly complex (e.g.,
    /// "Prove P != NP") and verbose tasks can be trivial.  The system
    /// parameter already encodes the right complexity class, so we use it
    /// directly without any task-length thresholds.
    fn try_archive_hit(&self, system: u8, _task_description: &str) -> Option<GenerateResult> {
        let _span = info_span!("topology_engine.archive_path").entered();

        if self.archive.cell_count() == 0 {
            debug!("archive_path_skip_empty");
            return None;
        }

        // Pure system-based descriptor — NO task_len heuristics.
        let (agent_count, max_depth) = match system {
            1 => (1u32, 1u32), // S1: solo agent, shallow
            2 => (3u32, 2u32), // S2: small team, medium depth
            3 => (5u32, 3u32), // S3: larger team, deeper collaboration
            _ => (2u32, 2u32), // default
        };

        let descriptor = BehaviorDescriptor::from_raw(agent_count, max_depth, 0.05, 0.5);

        if let Some(entry) = self.archive.get(&descriptor) {
            if entry.quality > 0.5 {
                let topology = entry.graph.clone();
                info!(
                    quality = entry.quality,
                    cost = entry.cost,
                    cell = ?descriptor.key(),
                    "archive_hit_found"
                );
                return Some(GenerateResult {
                    topology,
                    source: TopologySource::ArchiveHit,
                    confidence: entry.quality,
                });
            }
            debug!(quality = entry.quality, "archive_hit_quality_too_low");
        } else {
            debug!(cell = ?descriptor.key(), "archive_cell_empty");
        }

        None
    }

    /// Path 4: Try to mutate the best topology from the archive.
    fn try_mutation(&self) -> Option<GenerateResult> {
        let _span = info_span!("topology_engine.mutation_path").entered();

        let best = self.archive.best_by_quality()?;

        let graph = best.graph.clone();
        let mut rng = rand::rng();

        let stats = self.mutation_stats.lock().unwrap();
        let (op_idx, result) = apply_mutation_tracked(graph, &mut rng, &stats);
        drop(stats);

        match result {
            MutationResult::Success(mutated) => {
                let vr = self.verifier.verify(&mutated);
                if vr.valid {
                    self.mutation_stats
                        .lock()
                        .unwrap()
                        .record(op_idx as usize, true);
                    info!(
                        parent_quality = best.quality,
                        operator = super::mutations::OPERATOR_NAMES[op_idx as usize],
                        stats = %self.mutation_stats.lock().unwrap().summary(),
                        "mutation_success"
                    );
                    Some(GenerateResult {
                        topology: mutated,
                        source: TopologySource::Mutation,
                        confidence: best.quality * 0.8,
                    })
                } else {
                    self.mutation_stats
                        .lock()
                        .unwrap()
                        .record(op_idx as usize, false);
                    debug!(errors = ?vr.errors, "mutation_failed_verification");
                    None
                }
            }
            MutationResult::Invalid(reason) => {
                self.mutation_stats
                    .lock()
                    .unwrap()
                    .record(op_idx as usize, false);
                debug!(reason = %reason, "mutation_invalid");
                None
            }
        }
    }

    /// Path 5: Try MCTS search over mutation space (requires archive diversity).
    fn try_mcts_search(&self) -> Option<GenerateResult> {
        let _span = info_span!("topology_engine.mcts_path").entered();

        if self.archive.cell_count() < 5 {
            debug!(
                cells = self.archive.cell_count(),
                "mcts_path_skip_insufficient_diversity"
            );
            return None;
        }

        let best = self.archive.best_by_quality()?;

        let searcher = MctsSearcher::new(50, 100);
        if let Some(topology) = searcher.search(best.graph.clone()) {
            info!(parent_quality = best.quality, "mcts_search_success");
            Some(GenerateResult {
                topology,
                source: TopologySource::MctsSearch,
                confidence: best.quality * 0.85,
            })
        } else {
            debug!("mcts_search_no_result");
            None
        }
    }

    /// Path 6: Template fallback based on system tier.
    fn template_fallback(&self, system: u8) -> GenerateResult {
        let _span = info_span!("topology_engine.template_fallback", system = system).entered();

        // Empty model_id forces ModelAssigner to pick real models per-node
        // based on each node's system tier → multi-provider execution.
        // Previously hardcoded "gemini-2.5-flash" → all nodes same provider.
        let empty = "";
        let topology = match system {
            1 => templates::sequential(empty),
            2 => templates::avr(empty, empty),
            3 => templates::debate(empty, empty),
            _ => {
                warn!(
                    system = system,
                    "unknown_system_tier_defaulting_to_sequential"
                );
                templates::sequential(empty)
            }
        };

        GenerateResult {
            topology,
            source: TopologySource::TemplateFallback,
            confidence: 0.5, // moderate confidence for templates
        }
    }

    // ── Outcome recording ─────────────────────────────────────────────────

    /// Record the outcome of a topology execution.
    ///
    /// Feeds the result into:
    /// 1. S-MMU bridge (with structural features extracted from topology)
    /// 2. MAP-Elites archive (with behavior descriptor)
    /// 3. Bandit (adds arm for the topology's template)
    #[allow(clippy::too_many_arguments)]
    pub fn record_outcome(
        &mut self,
        smmu: &mut MultiViewMMU,
        topology_id: &str,
        task_summary: &str,
        keywords: Vec<String>,
        task_embedding: Option<Vec<f32>>,
        quality: f32,
        cost: f32,
        latency_ms: f32,
    ) {
        let _span = info_span!(
            "topology_engine.record_outcome",
            topology_id = topology_id,
            quality = quality,
            cost = cost,
        )
        .entered();

        // Extract structural features from cached topology (or use defaults).
        // Compute descriptor + raw features ONCE, reuse for S-MMU bridge and archive.
        let (agent_count, max_depth, model_diversity, template, descriptor) =
            if let Some(graph) = self.topology_cache.get(topology_id) {
                let (desc, raw) = BehaviorDescriptor::from_topology_with_raw(graph, cost);
                (
                    raw.agent_count,
                    raw.max_depth,
                    raw.model_diversity,
                    graph.template_type.clone(),
                    Some(desc),
                )
            } else {
                debug!(
                    topology_id = topology_id,
                    "topology_not_in_cache_using_defaults"
                );
                (1u32, 1u32, 0.0, "sequential".to_string(), None)
            };

        // 1. Feed S-MMU bridge
        let outcome = TopologyOutcome {
            topology_id: topology_id.to_string(),
            task_summary: task_summary.to_string(),
            keywords: keywords.clone(),
            task_embedding,
            template: template.clone(),
            quality,
            cost,
            latency_ms,
            agent_count,
            max_depth,
            model_diversity,
        };
        self.bridge.record_outcome(smmu, outcome);

        // 2. Feed MAP-Elites archive (reuses pre-computed descriptor)
        if let (Some(descriptor), Some(graph)) = (descriptor, self.topology_cache.get(topology_id))
        {
            let inserted =
                self.archive
                    .insert(&descriptor, graph.clone(), quality, cost, latency_ms);
            if inserted {
                info!(
                    cell = ?descriptor.key(),
                    quality = quality,
                    "archive_entry_inserted"
                );
            }
        }

        // 3. Feed bandit — use record_outcome() with last decision_id to update posteriors
        if let Some(ref decision_id) = self.last_decision_id {
            if let Err(e) = self
                .bandit
                .record_outcome(decision_id, quality, cost, latency_ms)
            {
                debug!(error = %e, "bandit_record_failed_fallback_to_add_arm");
                self.bandit.add_arm("observed", &template);
            }
        } else {
            self.bandit.add_arm("observed", &template);
        }

        self.outcomes_since_last_evolve += 1;

        info!(
            topology_id = topology_id,
            quality = quality,
            cost = cost,
            latency_ms = latency_ms,
            outcomes_since_last_evolve = self.outcomes_since_last_evolve,
            "outcome_recorded"
        );
    }

    // ── Evolution gating ──────────────────────────────────────────────────

    /// Determine whether online evolution should run.
    ///
    /// Returns `true` when all conditions are met:
    /// 1. Archive has >= `min_outcomes` recorded entries (enough data)
    /// 2. At least `cooldown_outcomes` new outcomes since last evolution
    /// 3. Archive coverage < 0.80 (diminishing returns above saturation)
    ///
    /// These thresholds are calibrated initial values, subject to ablation.
    pub fn should_evolve(&self, min_outcomes: usize, cooldown_outcomes: usize) -> bool {
        let cell_count = self.archive.cell_count();
        if cell_count < min_outcomes {
            return false;
        }
        if self.outcomes_since_last_evolve < cooldown_outcomes {
            return false;
        }
        // Coverage saturation check — stop evolving when archive is mostly full
        if self.archive.coverage() >= 0.80 {
            return false;
        }
        true
    }

    // ── Evolution ─────────────────────────────────────────────────────────

    /// Run a synchronous evolution loop on the archive.
    ///
    /// 1. Sample `pop_size` entries from archive (best-by-quality + random cells).
    /// 2. For each, apply 1-3 random mutations.
    /// 3. Validate survivors.
    /// 4. Insert into archive.
    /// 5. Repeat for `generations` rounds.
    pub fn evolve(&mut self, pop_size: usize, generations: usize) {
        let _span = info_span!(
            "topology_engine.evolve",
            pop_size = pop_size,
            generations = generations,
        )
        .entered();

        // Reset cooldown counter
        self.outcomes_since_last_evolve = 0;

        // Reset per-evolve op history. Python drains this buffer after
        // evolve() returns to emit per-child `evolution.mutation.applied` logs.
        self.last_applied_ops.lock().unwrap().clear();

        if self.archive.cell_count() == 0 {
            debug!("evolve_skip_empty_archive");
            return;
        }

        let mut rng = rand::rng();
        let mut total_mutations = 0u32;
        let mut total_successes = 0u32;

        for gen in 0..generations {
            let _gen_span = info_span!("evolve_generation", gen = gen).entered();

            // Sample population from archive
            let entries = self.archive.all_entries();
            if entries.is_empty() {
                break;
            }

            // Collect candidates: best + random sample
            let mut candidates: Vec<(TopologyGraph, f32, f32, f32)> = Vec::new();

            // Always include best-by-quality if available
            if let Some(best) = self.archive.best_by_quality() {
                candidates.push((best.graph.clone(), best.quality, best.cost, best.latency_ms));
            }

            // Fill rest from random cells
            let remaining = pop_size.saturating_sub(candidates.len());
            for _ in 0..remaining {
                if entries.is_empty() {
                    break;
                }
                let idx = rng.random_range(0..entries.len());
                let (_, entry) = &entries[idx];
                candidates.push((
                    entry.graph.clone(),
                    entry.quality,
                    entry.cost,
                    entry.latency_ms,
                ));
            }

            // Mutate each candidate 1-3 times
            for (graph, parent_quality, parent_cost, parent_latency) in candidates {
                let mutation_count = rng.random_range(1u32..=3);

                let mut current = Some(graph);

                for _ in 0..mutation_count {
                    total_mutations += 1;
                    let g = match current.take() {
                        Some(g) => g,
                        None => break,
                    };
                    // Use the tracked variant so Thompson-sampling stats and
                    // the per-evolve op-name buffer stay in sync. The buffer
                    // is drained by Python (`PyTopologyEngine.drain_last_applied_ops`)
                    // and surfaced as `evolution.mutation.applied` log lines.
                    let (op_idx, mutation_result) = {
                        let stats_guard = self.mutation_stats.lock().unwrap();
                        apply_mutation_tracked(g, &mut rng, &stats_guard)
                    };
                    let op_name = super::mutations::OPERATOR_NAMES
                        .get(op_idx as usize)
                        .copied()
                        .unwrap_or("unknown");
                    {
                        let mut ops = self.last_applied_ops.lock().unwrap();
                        // FIFO cap at 1024 so pathological configs can't grow
                        // the buffer unboundedly.
                        if ops.len() >= 1024 {
                            ops.remove(0);
                        }
                        ops.push(op_name.to_string());
                    }
                    match mutation_result {
                        MutationResult::Success(mutated) => {
                            self.mutation_stats
                                .lock()
                                .unwrap()
                                .record(op_idx as usize, true);
                            current = Some(mutated);
                        }
                        MutationResult::Invalid(_reason) => {
                            self.mutation_stats
                                .lock()
                                .unwrap()
                                .record(op_idx as usize, false);
                            // current stays None — signals invalid
                            break;
                        }
                    }
                }

                if let Some(final_graph) = current {
                    // Verify final result
                    let vr = self.verifier.verify(&final_graph);
                    if vr.valid {
                        let descriptor =
                            BehaviorDescriptor::from_topology(&final_graph, parent_cost);
                        // Estimate quality with a small discount
                        let est_quality = parent_quality * 0.95;
                        let inserted = self.archive.insert(
                            &descriptor,
                            final_graph,
                            est_quality,
                            parent_cost,
                            parent_latency,
                        );
                        if inserted {
                            total_successes += 1;
                        }
                    }
                }
            }
        }

        // ── CMA-ME continuous parameter refinement ──────────────────────────
        // After structural mutations, use the CMA emitter to optimise continuous
        // parameters (max_cost_usd, max_wall_time_s, edge_weight) on the archive
        // elites. Sample parameter vectors, apply them to copies of the best
        // topologies, score by parent quality, and feed back to the emitter.

        let cma_entries = self.archive.all_entries();
        if !cma_entries.is_empty() {
            let cma_n = pop_size.max(4); // at least 4 samples for CMA
            let cma_samples = self.cma_emitter.ask(cma_n);

            let mut cma_graphs: Vec<TopologyGraph> = Vec::new();
            let mut cma_fitnesses: Vec<f64> = Vec::new();

            for (i, params) in cma_samples.iter().enumerate() {
                // Pick a base entry (round-robin across archive entries)
                let (_, base_entry) = &cma_entries[i % cma_entries.len()];
                let mut graph = base_entry.graph.clone();

                // Apply CMA-sampled continuous params to ALL nodes (uniform scaling).
                // Per-node differentiation is a Phase C improvement.
                let inner = graph.inner_graph_mut();
                for node in inner.node_weights_mut() {
                    node.max_cost_usd = params[0] as f32;
                    node.max_wall_time_s = params[1] as f32;
                }

                // Apply edge weight to ALL edges (uniform scaling)
                for edge in inner.edge_weights_mut() {
                    edge.weight = params[2] as f32;
                }

                // Fitness: base quality (bounds already enforced by CmaEmitter)
                let fitness = base_entry.quality as f64;

                cma_fitnesses.push(fitness);
                cma_graphs.push(graph);
            }

            // Feed fitness back to CMA emitter
            self.cma_emitter.tell(&cma_samples, &cma_fitnesses);

            // Try to insert CMA-refined graphs into archive
            for (graph, &fitness) in cma_graphs.into_iter().zip(cma_fitnesses.iter()) {
                let vr = self.verifier.verify(&graph);
                if vr.valid {
                    let first_node = graph
                        .inner_graph()
                        .node_weight(petgraph::graph::NodeIndex::new(0));
                    let est_cost = first_node.map(|n| n.max_cost_usd).unwrap_or(0.05);
                    let descriptor = BehaviorDescriptor::from_topology(&graph, est_cost);
                    self.archive.insert(
                        &descriptor,
                        graph,
                        fitness as f32,
                        est_cost,
                        0.0, // latency unknown for CMA-refined
                    );
                }
            }

            debug!(
                cma_generation = self.cma_emitter.generation,
                cma_samples = cma_n,
                "cma_me_refinement_complete"
            );
        }

        info!(
            generations = generations,
            pop_size = pop_size,
            total_mutations = total_mutations,
            total_successes = total_successes,
            archive_cells = self.archive.cell_count(),
            cma_generation = self.cma_emitter.generation,
            "evolution_complete"
        );
    }
}

// ── Persistence (behind `cognitive` feature) ─────────────────────────────

#[cfg(feature = "cognitive")]
impl TopologyEngine {
    /// Save both bandit posteriors and MAP-Elites archive to a directory.
    ///
    /// Creates two SQLite files:
    /// - `{dir}/bandit_state.db` — arm posteriors, config (decay, exploration)
    /// - `{dir}/archive_state.db` — MAP-Elites grid cells with topology JSON
    ///
    /// Existing files are overwritten (WAL mode, UPSERT semantics).
    pub fn save_state(&self, dir: &str) -> Result<(), String> {
        let dir_path = std::path::Path::new(dir);
        std::fs::create_dir_all(dir_path).map_err(|e| format!("create dir {}: {}", dir, e))?;

        let bandit_path = dir_path.join("bandit_state.db");
        let archive_path = dir_path.join("archive_state.db");

        crate::routing::persistence::save_bandit(
            &self.bandit,
            bandit_path.to_str().ok_or("invalid bandit path")?,
        )?;

        self.archive
            .save_to_sqlite(archive_path.to_str().ok_or("invalid archive path")?)?;

        info!(
            dir = dir,
            bandit_arms = self.bandit.arm_count(),
            archive_cells = self.archive.cell_count(),
            "engine_state_saved"
        );

        Ok(())
    }

    /// Load bandit posteriors and MAP-Elites archive from a directory.
    ///
    /// Looks for `{dir}/bandit_state.db` and `{dir}/archive_state.db`.
    /// Missing files are silently skipped (cold start). Returns the count
    /// of items loaded as `(bandit_arms, archive_cells)`.
    pub fn load_state(&mut self, dir: &str) -> Result<(usize, usize), String> {
        let dir_path = std::path::Path::new(dir);

        let mut bandit_arms = 0usize;
        let mut archive_cells = 0usize;

        // Load bandit
        let bandit_path = dir_path.join("bandit_state.db");
        if bandit_path.exists() {
            let loaded = crate::routing::persistence::load_bandit(
                bandit_path.to_str().ok_or("invalid bandit path")?,
            )?;
            bandit_arms = loaded.arm_count();
            self.bandit = loaded;
            info!(arms = bandit_arms, "bandit_state_loaded");
        } else {
            debug!(path = ?bandit_path, "bandit_state_file_not_found_cold_start");
        }

        // Load archive
        let archive_path = dir_path.join("archive_state.db");
        if archive_path.exists() {
            let loaded = MapElitesArchive::load_from_sqlite(
                archive_path.to_str().ok_or("invalid archive path")?,
            )?;
            archive_cells = loaded.cell_count();
            self.archive = loaded;
            info!(cells = archive_cells, "archive_state_loaded");
        } else {
            debug!(path = ?archive_path, "archive_state_file_not_found_cold_start");
        }

        info!(
            dir = dir,
            bandit_arms = bandit_arms,
            archive_cells = archive_cells,
            "engine_state_loaded"
        );

        Ok((bandit_arms, archive_cells))
    }
}

impl Default for TopologyEngine {
    fn default() -> Self {
        Self::new()
    }
}

// ── Unit tests ──────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::memory::smmu::MultiViewMMU;
    use crate::topology::templates;

    #[test]
    fn test_new_engine_has_empty_cache() {
        let engine = TopologyEngine::new();
        assert_eq!(engine.topology_count(), 0);
    }

    #[test]
    fn test_new_engine_has_empty_archive() {
        let engine = TopologyEngine::new();
        assert_eq!(engine.archive().cell_count(), 0);
    }

    #[test]
    fn test_template_fallback_s1_sequential() {
        let engine = TopologyEngine::new();
        let result = engine.template_fallback(1);
        assert_eq!(result.source, TopologySource::TemplateFallback);
        assert_eq!(result.topology.template_type, "sequential");
        assert_eq!(result.topology.node_count(), 3);
    }

    #[test]
    fn test_template_fallback_s2_avr() {
        let engine = TopologyEngine::new();
        let result = engine.template_fallback(2);
        assert_eq!(result.source, TopologySource::TemplateFallback);
        assert_eq!(result.topology.template_type, "avr");
        assert_eq!(result.topology.node_count(), 3);
    }

    #[test]
    fn test_template_fallback_s3_debate() {
        let engine = TopologyEngine::new();
        let result = engine.template_fallback(3);
        assert_eq!(result.source, TopologySource::TemplateFallback);
        assert_eq!(result.topology.template_type, "debate");
        assert_eq!(result.topology.node_count(), 4);
    }

    #[test]
    fn test_cache_topology_and_get() {
        let mut engine = TopologyEngine::new();
        let graph = templates::sequential("test-model");
        let id = graph.id.clone();

        engine.cache_topology(graph);
        assert_eq!(engine.topology_count(), 1);

        let retrieved = engine.get_topology(&id);
        assert!(retrieved.is_some());
        assert_eq!(retrieved.unwrap().template_type, "sequential");
    }

    #[test]
    fn test_get_topology_missing() {
        let engine = TopologyEngine::new();
        assert!(engine.get_topology("nonexistent").is_none());
    }

    #[test]
    fn test_generate_empty_state_falls_back_to_template() {
        let mut engine = TopologyEngine::new();
        let mut smmu = MultiViewMMU::new();

        let result = engine.generate(&mut smmu, "Write a sorting function", None, 2, 0.5);
        assert_eq!(result.source, TopologySource::TemplateFallback);
        assert_eq!(result.topology.template_type, "avr");
    }

    #[test]
    fn test_topology_source_as_str() {
        assert_eq!(TopologySource::SmmuHit.as_str(), "smmu_hit");
        assert_eq!(TopologySource::ArchiveHit.as_str(), "archive_hit");
        assert_eq!(TopologySource::LlmSynthesis.as_str(), "llm_synthesis");
        assert_eq!(TopologySource::Mutation.as_str(), "mutation");
        assert_eq!(TopologySource::MctsSearch.as_str(), "mcts_search");
        assert_eq!(
            TopologySource::TemplateFallback.as_str(),
            "template_fallback"
        );
    }

    #[test]
    fn test_default_engine() {
        let engine = TopologyEngine::default();
        assert_eq!(engine.topology_count(), 0);
        assert_eq!(engine.archive().cell_count(), 0);
        assert_eq!(engine.bandit().arm_count(), 0);
        assert_eq!(engine.bridge().chunk_count(), 0);
    }

    #[test]
    fn test_generate_result_confidence_range() {
        let mut engine = TopologyEngine::new();
        let mut smmu = MultiViewMMU::new();

        let result = engine.generate(&mut smmu, "test task", None, 1, 0.0);
        assert!(result.confidence >= 0.0 && result.confidence <= 1.0);
    }

    #[test]
    fn test_evolve_uses_cma_emitter() {
        let mut engine = TopologyEngine::new();

        // Seed the archive with a valid topology so evolve() has something to work with.
        let graph = templates::sequential("gemini-2.5-flash");
        engine.cache_topology(graph.clone());

        let desc = super::super::map_elites::BehaviorDescriptor::from_raw(3, 2, 0.05, 0.5);
        engine.archive.insert(&desc, graph, 0.8, 0.05, 100.0);

        // CMA generation should be 0 before evolve.
        assert_eq!(engine.cma_emitter.generation, 0);

        // Run one generation of evolution.
        engine.evolve(4, 1);

        // CMA emitter should have been called (generation incremented).
        assert!(
            engine.cma_emitter.generation >= 1,
            "CMA emitter generation should be >= 1 after evolve, got {}",
            engine.cma_emitter.generation
        );
    }

    #[test]
    fn test_mcts_path_in_generate() {
        // This verifies the MCTS path doesn't break generate().
        // MCTS activates only with archive >= 5 cells, so normal generate still works.
        let mut engine = TopologyEngine::new();
        let mut smmu = MultiViewMMU::new();
        let result = engine.generate(&mut smmu, "test task", None, 2, 0.5);
        assert!(result.topology.node_count() > 0);
    }

    #[test]
    fn test_try_mcts_search_skips_when_archive_small() {
        let engine = TopologyEngine::new();
        // Empty archive should skip MCTS path.
        assert!(engine.try_mcts_search().is_none());
    }
}
