//! DynamicTopologyEngine — central orchestrator for task-adaptive topology generation.
//!
//! Ties together S-MMU retrieval, MAP-Elites archive lookup, mutation, LLM synthesis,
//! and evolution for generating custom multi-agent DAGs per task.
//!
//! # 5-path strategy (priority order)
//!
//! 1. **S-MMU hit**: Retrieve similar past task from S-MMU. If similarity > 0.7 AND quality > 0.5,
//!    clone that topology. Inject bandit priors.
//! 2. **Archive hit**: Compute `BehaviorDescriptor` from task heuristics, look up MAP-Elites archive.
//!    If found AND quality > 0.5, use it.
//! 3. **LLM synthesis**: Skip in pure Rust (Python side calls synthesize() directly).
//! 4. **Mutation**: Pick best-by-quality from archive, apply random mutation.
//! 5. **Template fallback**: S1→sequential, S2→avr, S3→debate.

use rand::Rng;
use std::collections::HashMap;
use tracing::{debug, info, info_span, warn};

use crate::memory::smmu::MultiViewMMU;
use crate::routing::bandit::ContextualBandit;

use super::cma_me::CmaEmitter;
use super::llm_synthesis::TopologySynthesizer;
use super::map_elites::{BehaviorDescriptor, MapElitesArchive};
use super::mutations::{apply_random_mutation, MutationResult};
use super::smmu_bridge::{TopologyOutcome, TopologySmmuBridge};
use super::templates;
use super::topology_graph::TopologyGraph;
use super::verifier::HybridVerifier;

// ── TopologySource ────────────────────────────────────────────────────────

/// How a topology was obtained by the engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TopologySource {
    /// Retrieved from similar past task via S-MMU.
    SmmuHit,
    /// Found in MAP-Elites archive.
    ArchiveHit,
    /// Generated by LLM (Python side).
    LlmSynthesis,
    /// Mutated from an existing topology.
    Mutation,
    /// Fell back to a built-in template.
    TemplateFallback,
}

impl TopologySource {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::SmmuHit => "smmu_hit",
            Self::ArchiveHit => "archive_hit",
            Self::LlmSynthesis => "llm_synthesis",
            Self::Mutation => "mutation",
            Self::TemplateFallback => "template_fallback",
        }
    }
}

// ── GenerateResult ────────────────────────────────────────────────────────

/// Result of `TopologyEngine::generate()`.
#[derive(Debug)]
pub struct GenerateResult {
    /// The generated topology graph.
    pub topology: TopologyGraph,
    /// How the topology was obtained.
    pub source: TopologySource,
    /// Confidence in the topology quality [0.0, 1.0].
    pub confidence: f32,
}

// ── TopologyEngine ────────────────────────────────────────────────────────

/// Central engine that orchestrates S-MMU retrieval, archive lookup, mutation,
/// LLM synthesis, and evolution for task-adaptive custom DAG generation.
pub struct TopologyEngine {
    bridge: TopologySmmuBridge,
    archive: MapElitesArchive,
    verifier: HybridVerifier,
    synthesizer: TopologySynthesizer,
    bandit: ContextualBandit,
    /// CMA-ME emitter for continuous parameter optimisation (cost, time, edge weight).
    cma_emitter: CmaEmitter,
    /// All known topologies by ULID id, for lazy-load from RoutingDecision.
    topology_cache: HashMap<String, TopologyGraph>,
}

impl TopologyEngine {
    /// Create a new engine with default bandit (decay=0.995, exploration=0.1).
    pub fn new() -> Self {
        Self {
            bridge: TopologySmmuBridge::new(),
            archive: MapElitesArchive::new(),
            verifier: HybridVerifier::new(),
            synthesizer: TopologySynthesizer::new(),
            bandit: ContextualBandit::create(0.995, 0.1),
            cma_emitter: CmaEmitter::new(3, 0.3),
            topology_cache: HashMap::new(),
        }
    }

    /// Accessor: read-only reference to the MAP-Elites archive.
    pub fn archive(&self) -> &MapElitesArchive {
        &self.archive
    }

    /// Accessor: read-only reference to the contextual bandit.
    pub fn bandit(&self) -> &ContextualBandit {
        &self.bandit
    }

    /// Accessor: read-only reference to the S-MMU bridge.
    pub fn bridge(&self) -> &TopologySmmuBridge {
        &self.bridge
    }

    /// Store a topology in the cache by its id.
    pub fn cache_topology(&mut self, graph: TopologyGraph) {
        self.topology_cache.insert(graph.id.clone(), graph);
    }

    /// Number of cached topologies.
    pub fn topology_count(&self) -> usize {
        self.topology_cache.len()
    }

    /// Lazy-load a topology from cache by ULID id.
    pub fn get_topology(&self, id: &str) -> Option<&TopologyGraph> {
        self.topology_cache.get(id)
    }

    // ── Core generation ───────────────────────────────────────────────────

    /// Generate a topology for a task using the 5-path strategy.
    ///
    /// # Arguments
    /// - `smmu`: The multi-view S-MMU for context retrieval.
    /// - `task_description`: Human-readable task description.
    /// - `task_embedding`: Optional 768-dim embedding for semantic search.
    /// - `system`: Cognitive system tier (1=S1, 2=S2, 3=S3).
    /// - `exploration_budget`: 0.0 = pure exploit, 1.0 = pure explore.
    pub fn generate(
        &mut self,
        smmu: &MultiViewMMU,
        task_description: &str,
        task_embedding: Option<Vec<f32>>,
        system: u8,
        exploration_budget: f32,
    ) -> GenerateResult {
        let _span = info_span!(
            "topology_engine.generate",
            system = system,
            exploration_budget = exploration_budget,
            task_len = task_description.len(),
        )
        .entered();

        // Path 1: S-MMU hit — retrieve similar past task
        if let Some(result) = self.try_smmu_hit(smmu, task_description, task_embedding.clone()) {
            info!(source = "smmu_hit", confidence = result.confidence, "topology_generated");
            return result;
        }

        // Path 2: Archive hit — look up MAP-Elites by behavior descriptor
        if let Some(result) = self.try_archive_hit(system) {
            info!(source = "archive_hit", confidence = result.confidence, "topology_generated");
            return result;
        }

        // Path 3: LLM synthesis — skipped in pure Rust (Python calls synthesize() directly)
        if exploration_budget > 0.3 && !self.synthesizer.is_rate_limited() {
            debug!("llm_synthesis_path_available_but_deferred_to_python");
        }

        // Path 4: Mutation — mutate best-by-quality from archive
        if let Some(result) = self.try_mutation() {
            info!(source = "mutation", confidence = result.confidence, "topology_generated");
            return result;
        }

        // Path 5: Template fallback
        let result = self.template_fallback(system);
        info!(
            source = "template_fallback",
            confidence = result.confidence,
            template = result.topology.template_type.as_str(),
            "topology_generated"
        );
        result
    }

    /// Path 1: Try to find a similar past task in S-MMU.
    fn try_smmu_hit(
        &mut self,
        smmu: &MultiViewMMU,
        _task_description: &str,
        _task_embedding: Option<Vec<f32>>,
    ) -> Option<GenerateResult> {
        let _span = info_span!("topology_engine.smmu_path").entered();

        // Need at least one chunk in the bridge to retrieve from
        if self.bridge.chunk_count() == 0 {
            debug!("smmu_path_skip_empty_bridge");
            return None;
        }

        // Register task as a query chunk in S-MMU to compare against stored outcomes.
        // We create a temporary MMU to hold the query so we don't mutate the shared one.
        // Instead, use the existing smmu directly for retrieval — register a temporary
        // query chunk would require &mut, which we don't have. So we scan bridge metadata
        // for the best match based on quality alone (simplified path).
        //
        // The full S-MMU semantic retrieval requires mutable access to register the query
        // chunk. Since `generate()` takes `&MultiViewMMU` (immutable), we fall through to
        // archive or mutation paths. The Python layer can call retrieve_similar() with a
        // properly registered query chunk before calling generate().

        let suggestions = self.bridge.retrieve_similar(smmu, 0, 5);

        // Find best suggestion with similarity > 0.7 AND quality > 0.5
        let best = suggestions
            .iter()
            .filter(|s| s.similarity_score > 0.7 && s.quality > 0.5)
            .max_by(|a, b| {
                a.similarity_score
                    .partial_cmp(&b.similarity_score)
                    .unwrap_or(std::cmp::Ordering::Equal)
            });

        if let Some(suggestion) = best {
            // Inject priors into bandit from all high-quality suggestions
            self.bridge.inject_priors(&mut self.bandit, &suggestions);

            // Try to clone the topology from cache
            if let Some(cached) = self.topology_cache.get(&suggestion.topology_id) {
                let topology = cached.clone();
                let confidence = suggestion.similarity_score * suggestion.quality;
                info!(
                    topology_id = %suggestion.topology_id,
                    similarity = suggestion.similarity_score,
                    quality = suggestion.quality,
                    "smmu_hit_found"
                );
                return Some(GenerateResult {
                    topology,
                    source: TopologySource::SmmuHit,
                    confidence,
                });
            }

            debug!(
                topology_id = %suggestion.topology_id,
                "smmu_hit_topology_not_in_cache"
            );
        }

        None
    }

    /// Path 2: Try to find a topology in the MAP-Elites archive.
    fn try_archive_hit(&self, system: u8) -> Option<GenerateResult> {
        let _span = info_span!("topology_engine.archive_path").entered();

        if self.archive.cell_count() == 0 {
            debug!("archive_path_skip_empty");
            return None;
        }

        // Estimate behavior descriptor from system tier heuristics
        let (agent_count, max_depth) = match system {
            1 => (1u32, 1u32),   // S1: solo agent, shallow
            2 => (3u32, 2u32),   // S2: small team, medium depth
            3 => (4u32, 3u32),   // S3: larger team, deeper
            _ => (2u32, 2u32),   // default
        };

        let descriptor = BehaviorDescriptor::from_raw(agent_count, max_depth, 0.05, 0.5);

        if let Some(entry) = self.archive.get(&descriptor) {
            if entry.quality > 0.5 {
                let topology = entry.graph.clone();
                info!(
                    quality = entry.quality,
                    cost = entry.cost,
                    cell = ?descriptor.key(),
                    "archive_hit_found"
                );
                return Some(GenerateResult {
                    topology,
                    source: TopologySource::ArchiveHit,
                    confidence: entry.quality,
                });
            }
            debug!(quality = entry.quality, "archive_hit_quality_too_low");
        } else {
            debug!(cell = ?descriptor.key(), "archive_cell_empty");
        }

        None
    }

    /// Path 4: Try to mutate the best topology from the archive.
    fn try_mutation(&self) -> Option<GenerateResult> {
        let _span = info_span!("topology_engine.mutation_path").entered();

        let best = self.archive.best_by_quality()?;

        let graph = best.graph.clone();
        let mut rng = rand::rng();

        match apply_random_mutation(graph, &mut rng) {
            MutationResult::Success(mutated) => {
                // Verify the mutation result
                let vr = self.verifier.verify(&mutated);
                if vr.valid {
                    info!(
                        parent_quality = best.quality,
                        "mutation_success"
                    );
                    Some(GenerateResult {
                        topology: mutated,
                        source: TopologySource::Mutation,
                        confidence: best.quality * 0.8, // discount for mutation uncertainty
                    })
                } else {
                    debug!(errors = ?vr.errors, "mutation_failed_verification");
                    None
                }
            }
            MutationResult::Invalid(reason) => {
                debug!(reason = %reason, "mutation_invalid");
                None
            }
        }
    }

    /// Path 5: Template fallback based on system tier.
    fn template_fallback(&self, system: u8) -> GenerateResult {
        let _span = info_span!("topology_engine.template_fallback", system = system).entered();

        let default_model = "gemini-2.5-flash";
        let topology = match system {
            1 => templates::sequential(default_model),
            2 => templates::avr(default_model, default_model),
            3 => templates::debate(default_model, default_model),
            _ => {
                warn!(system = system, "unknown_system_tier_defaulting_to_sequential");
                templates::sequential(default_model)
            }
        };

        GenerateResult {
            topology,
            source: TopologySource::TemplateFallback,
            confidence: 0.5, // moderate confidence for templates
        }
    }

    // ── Outcome recording ─────────────────────────────────────────────────

    /// Record the outcome of a topology execution.
    ///
    /// Feeds the result into:
    /// 1. S-MMU bridge (with structural features extracted from topology)
    /// 2. MAP-Elites archive (with behavior descriptor)
    /// 3. Bandit (adds arm for the topology's template)
    pub fn record_outcome(
        &mut self,
        smmu: &mut MultiViewMMU,
        topology_id: &str,
        task_summary: &str,
        keywords: Vec<String>,
        task_embedding: Option<Vec<f32>>,
        quality: f32,
        cost: f32,
        latency_ms: f32,
    ) {
        let _span = info_span!(
            "topology_engine.record_outcome",
            topology_id = topology_id,
            quality = quality,
            cost = cost,
        )
        .entered();

        // Extract structural features from cached topology (or use defaults)
        let (agent_count, max_depth, model_diversity, template) =
            if let Some(graph) = self.topology_cache.get(topology_id) {
                let desc = BehaviorDescriptor::from_topology(graph, cost);
                (
                    graph.node_count() as u32,
                    desc.max_depth_bucket as u32,
                    graph.node_count() as f32 / graph.node_count().max(1) as f32,
                    graph.template_type.clone(),
                )
            } else {
                debug!(topology_id = topology_id, "topology_not_in_cache_using_defaults");
                (1u32, 1u32, 0.0, "sequential".to_string())
            };

        // 1. Feed S-MMU bridge
        let outcome = TopologyOutcome {
            topology_id: topology_id.to_string(),
            task_summary: task_summary.to_string(),
            keywords: keywords.clone(),
            task_embedding,
            template: template.clone(),
            quality,
            cost,
            latency_ms,
            agent_count,
            max_depth,
            model_diversity,
        };
        self.bridge.record_outcome(smmu, outcome);

        // 2. Feed MAP-Elites archive
        if let Some(graph) = self.topology_cache.get(topology_id) {
            let descriptor = BehaviorDescriptor::from_topology(graph, cost);
            let inserted = self.archive.insert(
                &descriptor,
                graph.clone(),
                quality,
                cost,
                latency_ms,
            );
            if inserted {
                info!(
                    cell = ?descriptor.key(),
                    quality = quality,
                    "archive_entry_inserted"
                );
            }
        }

        // 3. Feed bandit
        self.bandit.add_arm("observed", &template);

        info!(
            topology_id = topology_id,
            quality = quality,
            cost = cost,
            latency_ms = latency_ms,
            "outcome_recorded"
        );
    }

    // ── Evolution ─────────────────────────────────────────────────────────

    /// Run a synchronous evolution loop on the archive.
    ///
    /// 1. Sample `pop_size` entries from archive (best-by-quality + random cells).
    /// 2. For each, apply 1-3 random mutations.
    /// 3. Validate survivors.
    /// 4. Insert into archive.
    /// 5. Repeat for `generations` rounds.
    pub fn evolve(&mut self, pop_size: usize, generations: usize) {
        let _span = info_span!(
            "topology_engine.evolve",
            pop_size = pop_size,
            generations = generations,
        )
        .entered();

        if self.archive.cell_count() == 0 {
            debug!("evolve_skip_empty_archive");
            return;
        }

        let mut rng = rand::rng();
        let mut total_mutations = 0u32;
        let mut total_successes = 0u32;

        for gen in 0..generations {
            let _gen_span = info_span!("evolve_generation", gen = gen).entered();

            // Sample population from archive
            let entries = self.archive.all_entries();
            if entries.is_empty() {
                break;
            }

            // Collect candidates: best + random sample
            let mut candidates: Vec<(TopologyGraph, f32, f32, f32)> = Vec::new();

            // Always include best-by-quality if available
            if let Some(best) = self.archive.best_by_quality() {
                candidates.push((
                    best.graph.clone(),
                    best.quality,
                    best.cost,
                    best.latency_ms,
                ));
            }

            // Fill rest from random cells
            let remaining = pop_size.saturating_sub(candidates.len());
            for _ in 0..remaining {
                if entries.is_empty() {
                    break;
                }
                let idx = rng.random_range(0..entries.len());
                let (_, entry) = &entries[idx];
                candidates.push((
                    entry.graph.clone(),
                    entry.quality,
                    entry.cost,
                    entry.latency_ms,
                ));
            }

            // Mutate each candidate 1-3 times
            for (graph, parent_quality, parent_cost, parent_latency) in candidates {
                let mutation_count = rng.random_range(1u32..=3);

                let mut current = Some(graph);

                for _ in 0..mutation_count {
                    total_mutations += 1;
                    let g = match current.take() {
                        Some(g) => g,
                        None => break,
                    };
                    match apply_random_mutation(g, &mut rng) {
                        MutationResult::Success(mutated) => {
                            current = Some(mutated);
                        }
                        MutationResult::Invalid(_reason) => {
                            // current stays None — signals invalid
                            break;
                        }
                    }
                }

                if let Some(final_graph) = current {
                    // Verify final result
                    let vr = self.verifier.verify(&final_graph);
                    if vr.valid {
                        let descriptor =
                            BehaviorDescriptor::from_topology(&final_graph, parent_cost);
                        // Estimate quality with a small discount
                        let est_quality = parent_quality * 0.95;
                        let inserted = self.archive.insert(
                            &descriptor,
                            final_graph,
                            est_quality,
                            parent_cost,
                            parent_latency,
                        );
                        if inserted {
                            total_successes += 1;
                        }
                    }
                }
            }
        }

        // ── CMA-ME continuous parameter refinement ──────────────────────────
        // After structural mutations, use the CMA emitter to optimise continuous
        // parameters (max_cost_usd, max_wall_time_s, edge_weight) on the archive
        // elites. Sample parameter vectors, apply them to copies of the best
        // topologies, score by parent quality, and feed back to the emitter.

        let cma_entries = self.archive.all_entries();
        if !cma_entries.is_empty() {
            let cma_n = pop_size.max(4); // at least 4 samples for CMA
            let cma_samples = self.cma_emitter.ask(cma_n);

            let mut cma_graphs: Vec<TopologyGraph> = Vec::new();
            let mut cma_fitnesses: Vec<f64> = Vec::new();

            for (i, params) in cma_samples.iter().enumerate() {
                // Pick a base entry (round-robin across archive entries)
                let (_, base_entry) = &cma_entries[i % cma_entries.len()];
                let mut graph = base_entry.graph.clone();

                // Apply CMA-sampled continuous params to the first node
                let inner = graph.inner_graph_mut();
                if let Some(first_node) = inner.node_weight_mut(petgraph::graph::NodeIndex::new(0))
                {
                    first_node.max_cost_usd = params[0] as f32;
                    first_node.max_wall_time_s = params[1] as f32;
                }

                // Apply edge weight to the first edge
                if let Some(first_edge) =
                    inner.edge_weights_mut().next()
                {
                    first_edge.weight = params[2] as f32;
                }

                // Fitness: base quality scaled by parameter reasonableness
                // (penalise extreme costs and times)
                let cost_penalty = if params[0] > 5.0 { 0.8 } else { 1.0 };
                let time_penalty = if params[1] > 5.0 { 0.9 } else { 1.0 };
                let fitness = base_entry.quality as f64 * cost_penalty * time_penalty;

                cma_fitnesses.push(fitness);
                cma_graphs.push(graph);
            }

            // Feed fitness back to CMA emitter
            self.cma_emitter.tell(&cma_samples, &cma_fitnesses);

            // Try to insert CMA-refined graphs into archive
            for (graph, &fitness) in cma_graphs.into_iter().zip(cma_fitnesses.iter()) {
                let vr = self.verifier.verify(&graph);
                if vr.valid {
                    let first_node = graph.inner_graph().node_weight(
                        petgraph::graph::NodeIndex::new(0),
                    );
                    let est_cost = first_node.map(|n| n.max_cost_usd).unwrap_or(0.05);
                    let descriptor = BehaviorDescriptor::from_topology(&graph, est_cost);
                    self.archive.insert(
                        &descriptor,
                        graph,
                        fitness as f32,
                        est_cost,
                        0.0, // latency unknown for CMA-refined
                    );
                }
            }

            debug!(
                cma_generation = self.cma_emitter.generation,
                cma_samples = cma_n,
                "cma_me_refinement_complete"
            );
        }

        info!(
            generations = generations,
            pop_size = pop_size,
            total_mutations = total_mutations,
            total_successes = total_successes,
            archive_cells = self.archive.cell_count(),
            cma_generation = self.cma_emitter.generation,
            "evolution_complete"
        );
    }
}

impl Default for TopologyEngine {
    fn default() -> Self {
        Self::new()
    }
}

// ── Unit tests ──────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::memory::smmu::MultiViewMMU;
    use crate::topology::templates;

    #[test]
    fn test_new_engine_has_empty_cache() {
        let engine = TopologyEngine::new();
        assert_eq!(engine.topology_count(), 0);
    }

    #[test]
    fn test_new_engine_has_empty_archive() {
        let engine = TopologyEngine::new();
        assert_eq!(engine.archive().cell_count(), 0);
    }

    #[test]
    fn test_template_fallback_s1_sequential() {
        let engine = TopologyEngine::new();
        let result = engine.template_fallback(1);
        assert_eq!(result.source, TopologySource::TemplateFallback);
        assert_eq!(result.topology.template_type, "sequential");
        assert_eq!(result.topology.node_count(), 3);
    }

    #[test]
    fn test_template_fallback_s2_avr() {
        let engine = TopologyEngine::new();
        let result = engine.template_fallback(2);
        assert_eq!(result.source, TopologySource::TemplateFallback);
        assert_eq!(result.topology.template_type, "avr");
        assert_eq!(result.topology.node_count(), 3);
    }

    #[test]
    fn test_template_fallback_s3_debate() {
        let engine = TopologyEngine::new();
        let result = engine.template_fallback(3);
        assert_eq!(result.source, TopologySource::TemplateFallback);
        assert_eq!(result.topology.template_type, "debate");
        assert_eq!(result.topology.node_count(), 4);
    }

    #[test]
    fn test_cache_topology_and_get() {
        let mut engine = TopologyEngine::new();
        let graph = templates::sequential("test-model");
        let id = graph.id.clone();

        engine.cache_topology(graph);
        assert_eq!(engine.topology_count(), 1);

        let retrieved = engine.get_topology(&id);
        assert!(retrieved.is_some());
        assert_eq!(retrieved.unwrap().template_type, "sequential");
    }

    #[test]
    fn test_get_topology_missing() {
        let engine = TopologyEngine::new();
        assert!(engine.get_topology("nonexistent").is_none());
    }

    #[test]
    fn test_generate_empty_state_falls_back_to_template() {
        let mut engine = TopologyEngine::new();
        let smmu = MultiViewMMU::new();

        let result = engine.generate(&smmu, "Write a sorting function", None, 2, 0.5);
        assert_eq!(result.source, TopologySource::TemplateFallback);
        assert_eq!(result.topology.template_type, "avr");
    }

    #[test]
    fn test_topology_source_as_str() {
        assert_eq!(TopologySource::SmmuHit.as_str(), "smmu_hit");
        assert_eq!(TopologySource::ArchiveHit.as_str(), "archive_hit");
        assert_eq!(TopologySource::LlmSynthesis.as_str(), "llm_synthesis");
        assert_eq!(TopologySource::Mutation.as_str(), "mutation");
        assert_eq!(TopologySource::TemplateFallback.as_str(), "template_fallback");
    }

    #[test]
    fn test_default_engine() {
        let engine = TopologyEngine::default();
        assert_eq!(engine.topology_count(), 0);
        assert_eq!(engine.archive().cell_count(), 0);
        assert_eq!(engine.bandit().arm_count(), 0);
        assert_eq!(engine.bridge().chunk_count(), 0);
    }

    #[test]
    fn test_generate_result_confidence_range() {
        let mut engine = TopologyEngine::new();
        let smmu = MultiViewMMU::new();

        let result = engine.generate(&smmu, "test task", None, 1, 0.0);
        assert!(result.confidence >= 0.0 && result.confidence <= 1.0);
    }

    #[test]
    fn test_evolve_uses_cma_emitter() {
        let mut engine = TopologyEngine::new();

        // Seed the archive with a valid topology so evolve() has something to work with.
        let graph = templates::sequential("gemini-2.5-flash");
        engine.cache_topology(graph.clone());

        let desc = super::super::map_elites::BehaviorDescriptor::from_raw(3, 2, 0.05, 0.5);
        engine.archive.insert(&desc, graph, 0.8, 0.05, 100.0);

        // CMA generation should be 0 before evolve.
        assert_eq!(engine.cma_emitter.generation, 0);

        // Run one generation of evolution.
        engine.evolve(4, 1);

        // CMA emitter should have been called (generation incremented).
        assert!(
            engine.cma_emitter.generation >= 1,
            "CMA emitter generation should be >= 1 after evolve, got {}",
            engine.cma_emitter.generation
        );
    }
}
